src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CarRepository::class)]
class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $mark = null;

    #[ORM\Column]
    private ?float $tarif = null;

    #[ORM\Column(length: 255)]
    private ?string $color = null;

    #[ORM\Column]
    private ?int $nbplace = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?User $user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\OneToMany(mappedBy: 'car', targetEntity: Reservation::class)]
    private Collection $reservations;

    #[ORM\Column]
    private ?bool $vintage = null;

    #[ORM\Column]
    private ?bool $climatisation = null;

    #[ORM\Column]
    private ?bool $decapotable = null;

    #[ORM\Column]
    private ?bool $toit_ouvrant = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?Type $type = null;

    #[ORM\OneToMany(mappedBy: 'Car', targetEntity: Favoris::class)]
    private Collection $favoris;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->favoris = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMark(): ?string
    {
        return $this->mark;
    }

    public function setMark(string $mark): self
    {
        $this->mark = $mark;

        return $this;
    }

    public function getTarif(): ?float
    {
        return $this->tarif;
    }

    public function setTarif(float $tarif): self
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getNbplace(): ?int
    {
        return $this->nbplace;
    }

    public function setNbplace(int $nbplace): self
    {
        $this->nbplace = $nbplace;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setCar($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getCar() === $this) {
                $reservation->setCar(null);
            }
        }

        return $this;
    }


    public function isVintage(): ?bool
    {
        return $this->vintage;
    }

    public function setVintage(bool $vintage): self
    {
        $this->vintage = $vintage;

        return $this;
    }

    public function isClimatisation(): ?bool
    {
        return $this->climatisation;
    }

    public function setClimatisation(bool $climatisation): self
    {
        $this->climatisation = $climatisation;

        return $this;
    }

    public function isDecapotable(): ?bool
    {
        return $this->decapotable;
    }

    public function setDecapotable(bool $decapotable): self
    {
        $this->decapotable = $decapotable;

        return $this;
    }

    public function isToitOuvrant(): ?bool
    {
        return $this->toit_ouvrant;
    }

    public function setToitOuvrant(bool $toit_ouvrant): self
    {
        $this->toit_ouvrant = $toit_ouvrant;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection<int, Favoris>
     */
    public function getFavoris(): Collection
    {
        return $this->favoris;
    }

    public function addFavori(Favoris $favori): self
    {
        if (!$this->favoris->contains($favori)) {
            $this->favoris->add($favori);
            $favori->setCar($this);
        }

        return $this;
    }

    public function removeFavori(Favoris $favori): self
    {
        if ($this->favoris->removeElement($favori)) {
            // set the owning side to null (unless already changed)
            if ($favori->getCar() === $this) {
                $favori->setCar(null);
            }
        }

        return $this;
    }
}

src/Form/CarType.php
<?php

namespace App\Form;

use App\Entity\Car;
use App\Entity\Type;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('mark',TextareaType::class,[
                'label'=>'Marque et date de sortie',
                "attr"=>[
                "class" =>"form-control",
                ]])
            ->add('tarif', NumberType::class,[
                'label'=>'Tarif par jour ',
                "attr"=>[
                "class" =>"form-control",
                ]])
            ->add('color', TextType::class,[
                'label'=>'Couleur',
                "attr"=>[
                    "class" =>"form-control",
                    ]])
             ->add('nbplace',IntegerType::class,[
                        'label'=>'Nombre de place',
                        "attr"=>[
                            "class" =>"form-control",
                            ]])
             ->add('type',null,[
                                "attr"=>[
                                    "class" =>"form-control",
                                ],
                                ])
            ->add('description',TextareaType::class,[
                                   'label'=>'Description',
                                   "attr"=>[
                                       "class" =>"form-control",
                                       ],
                               ])
            ->add('image', FileType::class,[
                                   "label"=>"Image",
                                   "attr"=>[
                                   "class" =>"form-control",
                                   ],
                                   "label" => false,
                                   "mapped" => false, 
                                   "multiple" => false
                               ])
            ->add('vintage',ChoiceType::class,[
                    'label'=>'Vintage : ',
                    'choices'=>[
                        'Oui'=>true,
                        'Non'=>false,
                    ],
                    'expanded'=>true,
                    'multiple'=>false,
            ])
            ->add('climatisation',ChoiceType::class,[
                'label'=>'Climatisation : ',
                'choices'=>[
                    'Oui'=>true,
                    'Non'=>false,
                ],
               
                'expanded'=>true,
                'multiple'=>false,
            ])
            ->add('decapotable',ChoiceType::class,[
                'label'=>'Décapotable : ',
                'choices'=>[
                    'Oui'=>true,
                    'Non'=>false,
                ],
                'expanded'=>true,
                'multiple'=>false,
            ])
            ->add('toit_ouvrant',ChoiceType::class,[
                'label'=>'Toit ouvrant : ',
                'choices'=>[
                    'Oui'=>true,
                    'Non'=>false,
                ],
                'expanded'=>true,
                'multiple'=>false,
             ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Car::class,
        ]);
    }
}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Form\CarType;
use App\Repository\CarRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/moncompte/car')]
class CarController extends AbstractController
{
    #[Route('/new', name: 'app_car_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CarRepository $carRepository): Response
    {
        $car = new Car();
        $user = $this->getUser();
        $form = $this->createForm(CarType::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image   = $form->get('image')->getData();
            $fichier = md5(uniqid()).'.'. $image->guessExtension();
            $image->move(
                $this->getParameter('images_directory'),
                $fichier
            );
            $car->setImage($fichier);
            $car->setUser($user);
            $car->setCreatedAt(new \DateTime("now"));
            $carRepository->save($car, true);
            $this->addFlash("success","Voiture enregistrée");
            return $this->redirectToRoute('app_mesvoitures', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('car/new.html.twig', [
            'car' => $car,
            'form' => $form,
            'title' => "Nouvelle voiture",
        ]);
    }

    #[Route('/{id}', name: 'app_car_show', methods: ['GET'])]
    public function show(Car $car): Response
    {
        return $this->render('car/show.html.twig', [
            'car' => $car,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_car_edit', methods: ['GET', 'POST'])]
    public function edit($id,Request $request, Car $car, CarRepository $carRepository): Response
    {
        $user = $this->getUser();
        $car=$carRepository->findOneById($id);
        $form = $this->createForm(CarType::class, $car);
        $form->handleRequest($request);

        if ($user===$car->getUser() && $form->isSubmitted() && $form->isValid()) {
            $carRepository->save($car, true);
            $this->addFlash("success","Voiture modifiée");
            return $this->redirectToRoute('app_mesvoitures', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('car/edit.html.twig', [
            'car' => $car,
            'form' => $form,
            'title' => "Modifier une voiture",
        ]);
    }

    #[Route('/remove/{id}', name: 'app_car_delete', methods: ['GET','POST'])]
    public function delete($id,Request $request, Car $car, CarRepository $carRepository): Response
    {
        $user = $this->getUser();
        $car=$carRepository->findOneById($id);
        if ( $user===$car->getUser() ) {
                $carRepository->remove($car, true);
        }

        $this->addFlash("danger","Voiture supprimée");
        return $this->redirectToRoute('app_mesvoitures', [], Response::HTTP_SEE_OTHER);
    }

}

templates/car/_form.html.twig
{{ form_start(form) }}
    <div class="text-center m-3 p-3">
        {{ form_row(form.mark) }}
        {{ form_row(form.tarif) }}
        {{ form_row(form.color) }}
        {{ form_row(form.nbplace) }}
        {{ form_row(form.type) }}
        {{ form_row(form.description) }}
         {{ form_row(form.image) }}
        <div class="row">
             <div class="col-md-3 border border-left">
                {{ form_row(form.vintage) }}
            </div>
             <div class="col-md-3 border border-left">
                {{ form_row(form.climatisation) }}
            </div>
            <div class="col-md-3 border border-left">
                {{ form_row(form.decapotable) }}
            </div>
            <div class="col-md-3 border border-left">
                {{ form_row(form.toit_ouvrant) }}
             </div>
         </div>
    </div>
    <div class="text-center mx-3">
        <button class="btn btn-danger">{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form) }}

templates/car/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{title}}{% endblock %}

{% block body %}
    <h3 class="text-center">Modifification d'une voiture :</h3>

    {{ include('car/_form.html.twig', {'button_label': 'Modifier'}) }}
    <a href="{{ path('app_mesvoitures') }}">Mes voitures</a>
{% endblock %}

templates/car/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{title}}{% endblock %}

{% block body %}
    <h2 class="text-center">Nouvelle voiture:</h2>

    {{ include('car/_form.html.twig') }}

    <a  class="m-4 text-danger" href="{{ path('app_mesvoitures') }}">Mes voitures</a>
{% endblock %}

templates/car/show.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <title>Karloco- Detail d'une voiture</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="#" type="image/x-icon" />
    <link rel="apple-touch-icon" href="#" />

    <link rel="stylesheet" href="{{asset("assets/home/css/bootstrap.min.css")}}" />
    <link rel="stylesheet" href="{{asset("assets/home/css/style.css")}}" />
    <link rel="stylesheet" href="{{asset("assets/home/css/style_banner.css")}}">
    <link rel="stylesheet" href="{{asset("assets/home/css/style_nav.css")}}">
    <link rel="stylesheet" href="{{asset("assets/home/css/style_carousel.css")}}">
    <link rel="stylesheet" href="{{asset("assets/home/css/responsive.css" )}}"/>
    <link rel="stylesheet" href="{{asset("assets/home/css/custom.css" )}}"/>
    <link rel="stylesheet" href="{{asset("assets/home/css/simplebar.css")}}"/>
    <link rel="stylesheet" href="{{asset("assets/home/css/owl.carousel.min.css")}}">
    <link rel="stylesheet" href="{{asset("assets/home/fonts/fontawesome-free-6.0.0-beta3-web/css/all.css")}}">
    <link rel="stylesheet" href="{{asset("assets/home/css/carousel.css" )}}"/>
    <link rel="stylesheet" href="{{asset("assets/home/css/carousel_3d.css")}}">
    <link rel="stylesheet" href="{{asset("assets/home/css/util.css")}}">
</head>

<body>
    <div data-simplebar style="width :100%; height: 100vh;">
    <div data-simplebar style="width :100%; height: 100vh;">


    
    <header class="top-header">
        <nav class="navbar header-nav navbar-expand-lg">
            <div class="container-fluid">
                <div class="navbar-brand">
                    <img src="/assets/home/images/logo.png" alt="image">
                    <div id="logo">&nbsp;Kar<span>LOCO</span></div>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-wd" aria-controls="navbar-wd" aria-expanded="false" aria-label="Toggle navigation">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbar-wd">
                    <ul class="navbar-nav" id="navs">
                        <li><a href="{{path("app_home")}}">Acceuil</a></li>
                        <li><a href="#voitures">Voitures</a></li>
                        <li><a href={{path("app_login")}}>Connexion</a></li>
                        <li><a href={{path("app_moncompte")}} class="intru">Mon compte</a></li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>

    <div class="section layout_padding_top">
        <div class="container">
                    <div class="row">
                        <a href="{{path("app_car_new")}}" class="btn  btn-custom_1 hvr-radial-out">Ajouter une voiture</a>
                    </div>
         </div>
                
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="full">
                        <div class="heading_main text_align_center">
						   <h2>Information de cette <span>voiture</span></h2>
                        </div>
					</div>
                </div>    
        <div class="container card p-3 my-1" style="width: 40rem;">
            <img src="/uploads/{{car.image}}" class="card-img-top" height="200px" width="200px" alt="...">
             <div class="card-body">
                  <h5 class="card-title"><i class="fa fa-automobile"></i>  Marque: {{car.mark}}, Type: {{car.type}}</h5>
                  <h6><i class="fa fa-right-long"></i> Vintage: {% if car.vintage %}"oui"{% else %}" Non"{% endif %}</h6>
                  <h6><i class="fa fa-right-long"></i> Climatisation: {% if car.climatisation %}"oui"{% else %}" Non"{% endif %}</h6>
                  <h6><i class="fa fa-right-long"></i> Décapotable: {% if car.decapotable %}"oui"{% else %}" Non"{% endif %}</h6>
                  <h6><i class="fa fa-right-long"></i> Toit ouvrant:{% if car.toitOuvrant %}"Oui"{% else %}"Non"{% endif %} </h6>
                  <h6><i class="fa fa-right-long"></i> couleur: {{car.color}}</h6>
                  <h6><i class="fa fa-right-long"></i> Nombre de place: {{car.nbplace}}</h6>
                  <h5>Description:</h5>
                    <p>{{car.description}}</p>
                  <h5><i class="fa fa-tag rotated"></i> Tarif: {{car.tarif}}Ar/Jour</h5>

            <div class="text-center">
                {% if car.user is same as (app.user) %}
                      <a href="{{ path('app_car_edit', {'id': car.id}) }}" class="btn  btn-custom_1 hvr-radial-out">Modifier</a>
                {%else%}
                    {#   <a href="{{path('app_favoris_new', {'car_id': car.id})}}" class="btn  btn-custom_1 hvr-radial-out">Ajouter aux favoris</a> #}
                     <a href="{{path('app_reservation_new', {'car_id': car.id})}}" class="btn  btn-custom_1 hvr-radial-out">Reserver</a>
                {%endif%}      
                
            </div>
            </div>
            </div>
                </div>
            </div>
        </div>  
       
    <footer class="bg-custom text-center text-white">
        <div class="container p-4 pb-0">
          <section class="mb-4">
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-facebook-f"></i
            ></a>
      
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-twitter"></i
            ></a>
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-google"></i
            ></a>
          </section>
        </div>
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2022 Copyright:
          <a class="text-white" href="">Karloco.mg</a>
        </div>
      </footer>
      

    <a href="#" id="scroll-to-top" class="hvr-radial-out"><i class="fa fa-angle-up"></i></a>

    <script src="{{asset("assets/home/js/jquery.min.js")}}></script>
	<script src="{{asset("assets/home/js/popper.min.js")}}></script>
    <script src="{{asset("assets/home/js/bootstrap.min.js")}}></script>
    <script src="{{asset("assets/home/js/jquery.magnific-popup.min.js")}}></script>
    <script src="{{asset("assets/home/js/jquery.pogo-slider.min.js")}}></script>
    <script src="{{asset("assets/home/js/slider-index.js")}}></script>
    <script src="{{asset("assets/home/js/form-validator.min.js")}}></script>
    <script src="{{asset("assets/home/js/contact-form-script.js")}}></script>
    <script src="{{asset("assets/home/js/isotope.min.js")}}></script>
    <script src="{{asset("assets/home/js/images-loded.min.js")}}></script>
    <script src="{{asset("assets/home/js/custom.js")}}></script>
    <script src="{{asset("assets/home/js/script.js")}}></script>
    <script src="{{asset("assets/home/js/owl.carousel.js")}}></script>
    <script src="{{asset("assets/home/js/carousel_custom.js")}}></script>
    <script src="{{asset("assets/home/js/slidebar.js")}}></script>
    <script src="{{asset("assets/home/js/carousel_3d.js")}}></script>
</div>
</div>
</body>

</html>